openapi: 3.1.0
info:
  title: Contacts
  description: Contacts API for managing contacts
  version: 1.0.0
servers:
  - url: 'https://api.dev.com/v1/'
    description: exemple server description
paths:
  /contacts:
    get:
      summary: Get contact list
      description: Get a list of contacts
      responses:
          '200':
            description: A list of contacts
            content:
                application/json:
                  schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Contact'
  /contacts/:reference:
    get:
      summary: Get contact by reference
      description: Get a contact by its reference
      parameters:
        - name: reference
          in: path
          description: Contact reference
          required: true
          schema:
            type: string
      responses:
          '200':
            description: A contact
            content:
                application/json:
                  schema:
                      $ref: '#/components/schemas/Contact'
          '401':
            description: Unauthorized
          '404':
            description: Contact not found
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout

components:
    schemas:
      Email:
        type: object
        properties:
          email:
            type: string
            description: Email address
          name:
            type: string
            description: Email name (eg. personal, work)
          default:
            type: boolean
            description: Default email
      Address:
        type: object
        properties:
          address:
            type: string
            description: Address
          city:
            type: string
            description: City
          postalCode:
            type: string
            description: Postal code
          country:
            type: string
            description: Country
          name:
            type: string
            description: Address name (eg. home, work)
          default:
            type: boolean
            description: Default address
      Phone:
        type: object
        properties:
          phone:
            type: string
            description: Phone number
          name:
            type: string
            description: Phone type name (eg. mobile, home, work)
          default:
            type: boolean
            description: Default phone
      Contact:
          type: object
          properties:
            reference:
              type: string
              description: Contact reference
            name:
              type: string
              description: Contact name
            emails:
              type: array of email
              description: Contact email
            phones:
              type: array of phone
              description: Contact phone
            address:
              type: array of address
              description: Contact address
