openapi: 3.0.3
info:
  title: Contacts
  description: Contacts API for managing contacts
  version: 1.0.0
servers:
  - url: 'https://api.dev.com/v1/'
    description: draft server description
paths:
  /contacts:
    get:
      operationId: getContacts
      summary: Get contact list
      description: Get a list of contacts
      responses:
          '200':
            description: A list of contacts
            content:
                application/json:
                  schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Contact'
          '401':
            description: Unauthorized
          '404':
            description: Contact not found
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout
  /contacts/:reference:
    get:
      operationId: getContact
      summary: Get contact by reference
      description: Get a contact by its reference
      parameters:
        - name: reference
          in: path
          description: Contact reference
          required: true
          schema:
            type: string
      responses:
          '200':
            description: A contact
            content:
                application/json:
                  schema:
                      $ref: '#/components/schemas/Contact'
          '401':
            description: Unauthorized
          '404':
            description: Contact not found
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout
    post:
      operationId: createContact
      summary: Create a new contact
      description: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
          '201':
            description: Contact created
            content:
                application/json:
                  schema:
                      $ref: '#/components/schemas/Contact'
          '400':
            description: Bad request
          '401':
            description: Unauthorized
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout
    put:
      operationId: updateContact
      summary: Update a contact
      description: Update a contact
      parameters:
        - name: reference
          in: path
          description: Contact reference
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
          '200':
            description: Contact updated
            content:
                application/json:
                  schema:
                      $ref: '#/components/schemas/Contact'
          '400':
            description: Bad request
          '401':
            description: Unauthorized
          '404':
            description: Contact not found
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout
    delete:
      operationId: deleteContact
      summary: Delete a contact
      description: Delete a contact
      parameters:
        - name: reference
          in: path
          description: Contact reference
          required: true
          schema:
            type: string
      responses:
          '204':
            description: Contact deleted
          '401':
            description: Unauthorized
          '404':
            description: Contact not found
          '500':
            description: Internal server error
          '503':
            description: Service unavailable
          '504':
            description: Gateway timeout
components:
    schemas:
      Email:
        type: object
        properties:
          email:
            type: string
            description: Email address
          name:
            type: string
            description: Email name (eg. personal, work)
          priority:
            type: integer
            description: Priority of email - the less is the more important
            default: 0
        required:
          - email
          - name
          - priority
      Address:
        type: object
        properties:
          address:
            type: string
            description: Address
          city:
            type: string
            description: City
          postalCode:
            type: string
            description: Postal code
          country:
            type: string
            description: Country
          name:
            type: string
            description: Address name (eg. home, work)
          default:
            type: boolean
            description: Default address
            default: false
        required:
          - name
          - default
          - address
          - city
          - postalCode
      Phone:
        type: object
        properties:
          phone:
            type: string
            description: Phone number
          name:
            type: string
            description: Phone type name (eg. mobile, home, work)
          priority:
            type: integer
            description: Priority of phone number - the less is the more important
            default: 0
        required:
          - phone
          - name
          - priority
      Contact:
          type: object
          properties:
            reference:
              type: string
              description: Contact reference
            name:
              type: string
              description: Contact name
            emails:
              type: array
              description: Contact email
              items:
                type: object
                $ref: '#/components/schemas/Email'
            phones:
              type: array
              description: Contact phone
              items:
                type: object
                $ref: '#/components/schemas/Phone'
            address:
              type: array
              description: Contact address
              items:
                type: object
                $ref: '#/components/schemas/Address'
          required:
            - reference
            - name